[workspace]
members = ["error_code", "error_code_derive"]
resolver = "2"
license = "MIT"

[workspace.dependencies]
error_code = { path = "./error_code" }
error_code_derive = { path = "./error_code_derive" }
